import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useData } from '../api/khranilishche';
import { Zagolovok } from '../komponenty/zagolovok';
import { FormaSobytiya } from '../komponenty/formaSobytiya';
import { segodnya } from '../util/daty';
export function Kalendar() {
  const d = useData(), me = d.users.find(u => u.id === d.currentUserId)!, members = d.users.filter(u => u.familyId === me.familyId);
  const [month, setMonth] = useState(new Date().getMonth()), [year, setYear] = useState(new Date().getFullYear()), [selected, setSelected] = useState(segodnya()), [type, setType] = useState('Все'), [member, setMember] = useState('all'), [form, setForm] = useState(false);
  const changeMonth = (delta: number) => { const date = new Date(year, month + delta, 1); setMonth(date.getMonth()); setYear(date.getFullYear()); setSelected(`${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-01`); };
  const days = new Date(year, month + 1, 0).getDate(), offset = (new Date(year, month, 1).getDay() + 6) % 7;
  const entries = [...d.events.filter(e => e.familyId === me.familyId).map(e => ({ ...e, link: '' })), ...d.tasks.filter(t => t.familyId === me.familyId && t.status !== 'archived').flatMap(t => [{ id: t.id, title: t.title, date: t.date, time: t.time, type: 'Задача', memberId: Array.isArray(t.assignees) ? t.assignees[0] : undefined, link: `/zadachi/${t.id}/pravka` }, { id: `${t.id}-deadline`, title: `Срок: ${t.title}`, date: t.deadline.slice(0, 10), time: t.deadline.slice(11, 16), type: 'Дедлайн', memberId: Array.isArray(t.assignees) ? t.assignees[0] : undefined, link: `/zadachi/${t.id}/pravka` }])].filter(e => (type === 'Все' || e.type === type) && (member === 'all' || e.memberId === member || !e.memberId));
  const agenda = entries.filter(e => e.date === selected).sort((a, b) => a.time.localeCompare(b.time));
  return <><Zagolovok title="Календарь" subtitle="Дела, встречи и семейные планы." /><div className="calendar-layout"><section className="panel calendar-panel"><div className="calendar-top"><button className="icon-button" onClick={() => changeMonth(-1)} aria-label="Предыдущий месяц">‹</button><h2>{new Date(year, month).toLocaleDateString('ru-RU', { month: 'long', year: 'numeric' })}</h2><button className="icon-button" onClick={() => changeMonth(1)} aria-label="Следующий месяц">›</button></div><div className="calendar-filters"><select aria-label="Тип события" value={type} onChange={e => setType(e.target.value)}>{['Все', 'Задача', 'Дедлайн', 'День рождения', 'Встреча', 'Прогулка', 'Поездка', 'Другое'].map(x => <option key={x}>{x}</option>)}</select><select aria-label="Участник" value={member} onChange={e => setMember(e.target.value)}><option value="all">Все участники</option>{members.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div className="calendar-grid">{['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'].map(x => <strong key={x}>{x}</strong>)}{Array.from({ length: offset }, (_, i) => <span key={`empty-${i}`} />)}{Array.from({ length: days }, (_, i) => { const date = `${year}-${String(month + 1).padStart(2, '0')}-${String(i + 1).padStart(2, '0')}`; return <button key={date} className={`${selected === date ? 'selected' : ''} ${date === segodnya() ? 'today' : ''}`} onClick={() => setSelected(date)} aria-label={`${i + 1} число, ${entries.filter(e => e.date === date).length} событий`}>{i + 1}{entries.some(e => e.date === date) && <i />}</button>; })}</div></section><aside className="agenda"><div className="section-title"><h2>{new Date(`${selected}T12:00:00`).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' })}</h2><button className="small-button" onClick={() => setForm(true)}>+ Событие</button></div>{form && <FormaSobytiya members={members} onClose={() => setForm(false)} />}{agenda.length ? agenda.map(e => <div className="agenda-item" key={e.id}><time>{e.time}</time><div><b>{e.title}</b><span>{e.type}{e.memberId ? ` · ${members.find(u => u.id === e.memberId)?.name}` : ''}</span></div>{e.link && <Link to={e.link} aria-label={`Открыть ${e.title}`}>→</Link>}</div>) : <p className="muted">На этот день событий нет.</p>}</aside></div></>;
}
