import { useState } from 'react';
import { useData } from '../api/khranilishche';
import { izmenitSemyu, reshitZapros } from '../api/semyaApi';
import { Zagolovok } from '../komponenty/zagolovok';
export function Semya() {
  const d = useData(), me = d.users.find(u => u.id === d.currentUserId)!, family = d.families.find(f => f.id === me.familyId)!, members = d.users.filter(u => u.familyId === family.id), requests = d.requests.filter(r => r.familyId === family.id);
  const [name, setName] = useState(family.name), [copied, setCopied] = useState(false);
  return <><Zagolovok title="Наша семья" subtitle="Общий дом и его участники." /><div className="family-grid"><section className="panel"><p className="eyebrow">Название семьи</p><h2>{family.name}</h2><p className="muted">Код приглашения</p><div className="invite-code"><strong>{family.code}</strong><button className="small-button" onClick={async () => { await navigator.clipboard.writeText(family.code); setCopied(true); }}> {copied ? 'Скопировано' : 'Скопировать'}</button></div><p className="muted">Код помогает найти семью, но не заменяет вход в аккаунт. Взрослого участника должен подтвердить другой взрослый.</p></section><section className="panel"><h2>Участники</h2><div className="members-list">{members.map(u => <div className="person-line" key={u.id}><span className="avatar small">{u.avatar}</span><strong>{u.name}</strong><span>{u.role === 'adult' ? 'Взрослый' : 'Ребёнок'}</span></div>)}</div></section>{me.role === 'adult' && <><section className="panel"><h2>Запросы на вступление</h2>{requests.length ? requests.map(r => <div className="request-line" key={r.id}><span>{d.users.find(u => u.id === r.userId)?.name}</span><div><button className="small-button" onClick={() => reshitZapros(r.id, true)}>Принять</button><button className="text-button" onClick={() => reshitZapros(r.id, false)}>Отклонить</button></div></div>) : <p className="muted">Новых запросов нет.</p>}</section><section className="panel"><h2>Настройки семьи</h2><form onSubmit={e => { e.preventDefault(); izmenitSemyu(name, family.mood); }}><label>Название<input value={name} onChange={e => setName(e.target.value)} minLength={2} required /></label><button className="button">Сохранить</button></form></section></>}</div></>;
}
