import { useSyncExternalStore } from 'react';
import type { Dannye } from '../tipy/tipy';
import { primer } from '../dannye/primer';
const KEY = 'dom-dela-demo-v1';
export const serverMode = Boolean(import.meta.env.VITE_API_URL);
const read = (): Dannye => { try { return JSON.parse(localStorage.getItem(KEY) || 'null') || primer(); } catch { return primer(); } };
const empty = (): Dannye => ({ users: [], families: [], tasks: [], events: [], messages: [], history: [], notifications: [], requests: [], settings: { reminders: true } });
let current = serverMode ? empty() : read();
const listeners = new Set<() => void>();
export const getData = () => current;
const publish = () => listeners.forEach(fn => fn());
export const setData = (change: (data: Dannye) => Dannye) => { current = change(current); if (!serverMode) localStorage.setItem(KEY, JSON.stringify(current)); publish(); };
export const replaceData = (data: Dannye) => { current = data; publish(); };
export const useData = () => useSyncExternalStore(fn => { listeners.add(fn); return () => listeners.delete(fn); }, getData);
export const resetDemo = () => { if (serverMode) return; current = primer(); localStorage.setItem(KEY, JSON.stringify(current)); publish(); };
